[tool.poetry]
name = "fs-schema-validator"
version = "0.1.0"
description = ""
authors = ["Federico Ravasio <fr@nablaflow.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

click = "~8.1"
parsita = "~1.7"
pillow = "~10.3"
pydantic = "~2.7"
pygltflib = "~1.16"
pyyaml = "~6.0"
sortedcontainers = "~2.4"
svglib = "~1.5"

[tool.poetry.group.dev.dependencies]
mypy = "~1.10"
orjson = "~3.10"
pytest = "~8.2"
rich = "~13.7"
ruff = "~0.4.3"
types-pillow = "~10.2.0"
types-pyyaml = "~6.0.12"

[tool.poetry.scripts]
validate_schema = 'fs_schema_validator.__main__:validate'

[tool.pytest.ini_options]
addopts = "-vv"
pythonpath = "."

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["E", "F", "I", "W", "N", "DTZ", "RET", "SIM", "RUF"]
ignore = ["E501", "ANN101", "ANN102"]

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
follow_imports = 'silent'
no_implicit_reexport = true
show_error_codes = true
strict_optional = false
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = [
  "parsita",
  "pygltflib",
  "sortedcontainers",
  "svglib",
]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
