[tool.poetry]
name = "fs-schema-validator"
version = "0.1.0"
description = ""
authors = ["Federico Ravasio <fr@nablaflow.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

click = "~8.1.7"
orjson = "=3.9.10"
parsita = "~1.7.2"
pillow = "~10.1.0"
pydantic = "~1.10"
pygltflib = "~1.16.1"
pyyaml = "~6.0.1"
sortedcontainers = "~2.4.0"
svgelements = "=1.9.1"

[tool.poetry.group.dev.dependencies]
black = "~23.11"
isort = "~5.12"
mypy = "~1.7"
pytest = "~7.4"
rich = "~13.7"
types-pillow = "~10.1.0"
types-pyyaml = "~6.0.1"

[tool.poetry.scripts]
validate_schema = 'fs_schema_validator.__main__:validate'

[tool.pytest.ini_options]
addopts = "-vv"
pythonpath = "."

[tool.black]
line-length = 90
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 90
multi_line_output = 3

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
follow_imports = 'silent'
no_implicit_reexport = true
show_error_codes = true
strict_optional = false
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = [
  "parsita",
  "pygltflib",
  "sortedcontainers",
  "svgelements",
]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
