bindings:
  range: [0, 2]
  enum:
    - foo
    - bar

schema:
  - type: image
    format: png
    path: image.png

  - type: image
    format: webp
    path: image.webp

  - type: image
    format: jpeg
    path: image.jpg

  - type: image
    format: png
    path: not-a-png.png

  - type: gltf
    format: glb
    path: asset.glb

  - type: gltf
    format: glb
    path: corrupted-asset.glb

  - type: gltf
    format: gltf
    path: asset.gltf

  - type: gltf
    format: gltf
    path: corrupted-asset.gltf

  - type: gltf
    format: glb
    path: asset-{$range}.glb

  - type: gltf
    format: glb
    path: asset-{$range}-{$enum}.glb

  - type: json
    path: info.json
    spec: 
      type: object
      attrs:
        colormap:
          type: int
          min: 0
        bool:
          type: bool
        array:
          type: array
          unique_items: true
          min_items: 1
          items:
            type: int
        tuple:
          type: fixed_array
          items:
            - type: int
            - type: str
            - type: float
        mag_u:
          type: float
          min: 0.0
          max: 10.0
        foo:
          type: str
        nested:
          type: object
          attrs:
            foo:
              type: float
